#- label: ":jest: test"
#  command: "auto/test"
#  env:
#    AWS_DEFAULT_REGION: eu-west-1
#    ENV: staging
#    BUCKET_NAME: keystone-btcsnap-eu-west-1
#  agents:
#     queue: keystone-staging:build

#- wait

- block: 'Publish to staging?'
  branches: '!master'

- label: ':amazon-s3: publish to staging'
  command: 'auto/publish'
  agents:
    queue: keystone-staging:deploy
  concurrency: 1
  concurrency_group: 'keystone-staging/publish'
  env:
    AWS_DEFAULT_REGION: eu-west-1
    ENV: staging
    BUCKET_NAME: keystone-btcsnap-eu-west-1

- block: 'Publish to productions?'
  branches: 'master'

- label: ':amazon-s3: publish to production'
  command: 'auto/publish'
  branches: 'master'
  agents:
    queue: keystone-production:deploy
  concurrency: 1
  concurrency_group: 'keystone-production/publish'
  env:
    ENV: production
    AWS_DEFAULT_REGION: eu-central-1
    BUCKET_NAME: keystone-btcsnap-eu-central-1
